# 项目名称、版本、版权年份
dfyy:
  name: dfyy
  version: 1.1.1
  copyrightYear: 2018
  #视频上传地址  #图片上传地址
  profile: E:/profile/
  imgfile: E:/imgfile/
#  profile: /server/project/dfyy/profile/
#  imgfile: /server/project/dfyy/imgfile/
#开发环境配置
server:
  #端口
  port: 80
  tomcat:
    uri-encoding: utf-8
#日志配置
logging:
  level:
    com.dfyy: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
#用户配置
user:
  password:
    #密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5   
#Spring配置
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  messages:
    #国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  http:
    multipart:
      max-file-size: 1000Mb
      max-request-size: 1000Mb
  devtools:
    restart:
      enabled: true    
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.dfyy.project
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
# PageHelper
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
# 代码生成
gen: 
  # 作者
  author: dfyy
  # 默认生成包路径 module 需改成自己的模块名称 如 system monitor tool
  packageName: com.dfyy.project.module
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀(类名不会包含表前缀)
  tablePrefix: sys_